### ISSUE TITLE
is rgba Color creation supported?

### ISSUE THREAD

**Issue by gamecubate** [janet-lang/jaylib#29]
Hi. This lib is really good. Thanks for that.

How do I create a color with transparency? `(color-alpha 255 0 0 255)` seems a no-show.

**Comment by gamecubate** [comment]
Oh. It looks like that may not have been implemented yet.
```
api.txt:
...
// Color-related functions
[ ] int ColorToInt(Color color)
[ ] Vector4 ColorNormalize(Color color)
[ ] Vector3 ColorToHSV(Color color)
[ ] Color ColorFromHSV(Vector3 hsv)
[ ] Color GetColor(int hexValue)
[ ] Color Fade(Color color, float alpha)
```

**Comment by gamecubate** [comment]
Never mind. I figured it out. 

```
(draw-circle cx cy r [1 0 0 0.5])
```

**Comment by wmealing** [comment]
In case anyone else trips over this, the [1 0 0 0.5] above is. Red Green Blue Alpha, with values between 0 and 1 inclusive.

**Comment by wmealing** [comment]
Here is a function that i'm using that accepts the original value (0-255) and converts it as a value usable for jaylib.

(defn color-alpha [r g b a]
  [(/ r 255.0)
   (/ g 255.0)
   (/ b 255.0)
   (/ a 255.0)])

(color-alpha 128 128 128 20)

**Comment by sogaiu** [comment]
> In case anyone else trips over this, the [1 0 0 0.5] above is. Red Green Blue Alpha, with values between 0 and 1 inclusive.

Some possibly relevant source lines for reference:

* [link between `draw-circle` and `cfun_DrawCircle`](https://github.com/janet-lang/jaylib/blob/4875309941972529777ef64555e73c600916e48f/src/shapes.h#L492-L495)
* [inside `cfun_DrawCircle`](https://github.com/janet-lang/jaylib/blob/4875309941972529777ef64555e73c600916e48f/src/shapes.h#L83)
* [inside `jaylib_getcolor`](https://github.com/janet-lang/jaylib/blob/4875309941972529777ef64555e73c600916e48f/src/types.h#L282-L287)
