### ISSUE TITLE
Use TCC instead of MS VS or GCC on Windows?

### ISSUE THREAD

**Issue by rpherman** [janet-lang/jaylib#7]
Is it possible to use TCC and the Raylib TCC version with Janet on Windows? Thanks!

**Comment by profan** [comment]
clang-cl: https://clang.llvm.org/docs/UsersManual.html#clang-cl may also be an option here, I made a fair bit of progress getting things working this way, just stuck on some linker errors involving glfw right now, but might be able to work it out (and will probably PR any changes necessary to get it to build if I can work it out).

**Comment by rpherman** [comment]
I am also playing with Zig's drop-in gcc/clang command: zig cc
It has a ton of cross compilation targets.

**Comment by yumaikas** [comment]
So, at least as of today, it compiles and works on windows using just cl.exe.
